/*
Navicat MySQL Data Transfer

Source Server         : server
Source Server Version : 50568
Source Host           : 127.0.0.1:3306
Source Database       : mion

Target Server Type    : MYSQL
Target Server Version : 50568
File Encoding         : 65001

Date: 2023-03-09 10:14:31
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for alerts
-- ----------------------------
DROP TABLE IF EXISTS `alerts`;
CREATE TABLE `alerts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `type` enum('comercial','verificacion','cliente') DEFAULT NULL,
  `nif` varchar(255) DEFAULT NULL,
  `codigo_comercial` varchar(255) DEFAULT NULL,
  `numero_telf` varchar(255) DEFAULT NULL,
  `nota` varchar(9999) DEFAULT NULL,
  `fecha` datetime(6) DEFAULT NULL,
  `user_added` varchar(255) DEFAULT NULL,
  `verificacion` varchar(255) DEFAULT NULL,
  `hidden` enum('1','0') DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=77 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for chat
-- ----------------------------
DROP TABLE IF EXISTS `chat`;
CREATE TABLE `chat` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user` varchar(255) DEFAULT NULL,
  `message` varchar(9999) DEFAULT NULL,
  `date` varchar(255) DEFAULT NULL,
  `prefijo` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=104 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for cigs
-- ----------------------------
DROP TABLE IF EXISTS `cigs`;
CREATE TABLE `cigs` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `num` varchar(255) NOT NULL,
  `fecha` varchar(255) DEFAULT NULL,
  `user_intro` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for click_comerciales
-- ----------------------------
DROP TABLE IF EXISTS `click_comerciales`;
CREATE TABLE `click_comerciales` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `distribuidor` varchar(255) DEFAULT NULL,
  `gerente` varchar(255) DEFAULT NULL,
  `subgerente` varchar(255) DEFAULT NULL,
  `oficina` varchar(255) DEFAULT NULL,
  `zona_edp` varchar(255) DEFAULT NULL,
  `codigo_interno` varchar(255) DEFAULT NULL,
  `nombre` varchar(255) DEFAULT NULL,
  `primer_apellido` varchar(255) DEFAULT NULL,
  `segundo_apellido` varchar(255) DEFAULT NULL,
  `nif` varchar(255) DEFAULT NULL,
  `laboral` varchar(255) DEFAULT NULL,
  `fecha_alta` varchar(255) DEFAULT NULL,
  `petic` varchar(255) DEFAULT NULL,
  `recep` varchar(255) DEFAULT NULL,
  `fecha_baja` varchar(255) DEFAULT NULL,
  `observaciones` varchar(999) DEFAULT NULL,
  `observaciones_2` varchar(999) DEFAULT NULL,
  `observaciones_3` varchar(999) DEFAULT NULL,
  `observaciones_style` varchar(999) DEFAULT NULL,
  `estado` varchar(255) DEFAULT '#4caf50',
  `cara` varchar(255) DEFAULT NULL,
  `dni_1` varchar(255) DEFAULT NULL,
  `dni_2` varchar(255) DEFAULT NULL,
  `estadouser` enum('1','0') DEFAULT '1',
  `poblacion_comercial` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1584 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for click_comerciales_evolucion
-- ----------------------------
DROP TABLE IF EXISTS `click_comerciales_evolucion`;
CREATE TABLE `click_comerciales_evolucion` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `codigo_comercial` varchar(255) DEFAULT NULL,
  `fecha_alta` varchar(255) DEFAULT NULL,
  `fecha_baja` varchar(255) DEFAULT NULL,
  `fecha` varchar(255) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=357 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for click_distribuidores
-- ----------------------------
DROP TABLE IF EXISTS `click_distribuidores`;
CREATE TABLE `click_distribuidores` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for click_gerentes
-- ----------------------------
DROP TABLE IF EXISTS `click_gerentes`;
CREATE TABLE `click_gerentes` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `distribuidor` varchar(255) DEFAULT NULL,
  `gerente` varchar(255) DEFAULT NULL,
  `subgerente` varchar(255) DEFAULT NULL,
  `oficina` varchar(255) DEFAULT NULL,
  `codigo_interno` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=149 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for click_gerentes_comisiones
-- ----------------------------
DROP TABLE IF EXISTS `click_gerentes_comisiones`;
CREATE TABLE `click_gerentes_comisiones` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `gerente` varchar(255) DEFAULT NULL,
  `subgerente` varchar(255) DEFAULT NULL,
  `oficina` varchar(255) DEFAULT NULL,
  `codigo_gerente` varchar(255) DEFAULT NULL,
  `provincia` varchar(255) DEFAULT NULL,
  `provincia_price` decimal(10,0) DEFAULT NULL,
  `we_dia` varchar(255) DEFAULT NULL,
  `we_mes` varchar(255) DEFAULT NULL,
  `we_ano` varchar(11) DEFAULT NULL,
  `residencial_1_mercantil_1` varchar(255) DEFAULT NULL,
  `residencial_1_mercantil_2` varchar(255) DEFAULT NULL,
  `residencial_1_mercantil_3` varchar(255) DEFAULT NULL,
  `residencial_1_laboral_1` varchar(255) DEFAULT NULL,
  `residencial_1_laboral_2` varchar(255) DEFAULT NULL,
  `residencial_1_laboral_3` varchar(255) DEFAULT NULL,
  `residencial_2_mercantil_1` varchar(255) DEFAULT NULL,
  `residencial_2_mercantil_2` varchar(255) DEFAULT NULL,
  `residencial_2_mercantil_3` varchar(255) DEFAULT NULL,
  `residencial_2_laboral_1` varchar(255) DEFAULT NULL,
  `residencial_2_laboral_2` varchar(255) DEFAULT NULL,
  `residencial_2_laboral_3` varchar(255) DEFAULT NULL,
  `residencial_3_mercantil_1` varchar(255) DEFAULT NULL,
  `residencial_3_mercantil_2` varchar(255) DEFAULT NULL,
  `residencial_3_mercantil_3` varchar(255) DEFAULT NULL,
  `residencial_3_laboral_1` varchar(255) DEFAULT NULL,
  `residencial_3_laboral_2` varchar(255) DEFAULT NULL,
  `residencial_3_laboral_3` varchar(255) DEFAULT NULL,
  `residencial_4_mercantil_1` varchar(255) DEFAULT NULL,
  `residencial_4_mercantil_2` varchar(255) DEFAULT NULL,
  `residencial_4_mercantil_3` varchar(255) DEFAULT NULL,
  `residencial_4_laboral_1` varchar(255) DEFAULT NULL,
  `residencial_4_laboral_2` varchar(255) DEFAULT NULL,
  `residencial_4_laboral_3` varchar(255) DEFAULT NULL,
  `residencial_5_mercantil_1` varchar(255) DEFAULT NULL,
  `residencial_5_mercantil_2` varchar(255) DEFAULT NULL,
  `residencial_5_mercantil_3` varchar(255) DEFAULT NULL,
  `residencial_5_laboral_1` varchar(255) DEFAULT NULL,
  `residencial_5_laboral_2` varchar(255) DEFAULT NULL,
  `residencial_5_laboral_3` varchar(255) DEFAULT NULL,
  `residencial_6_mercantil_1` varchar(255) DEFAULT NULL,
  `residencial_6_mercantil_2` varchar(255) DEFAULT NULL,
  `residencial_6_mercantil_3` varchar(255) DEFAULT NULL,
  `residencial_6_laboral_1` varchar(255) DEFAULT NULL,
  `residencial_6_laboral_2` varchar(255) DEFAULT NULL,
  `residencial_6_laboral_3` varchar(255) DEFAULT NULL,
  `residencial_7_mercantil_1` varchar(255) DEFAULT NULL,
  `residencial_7_mercantil_2` varchar(255) DEFAULT NULL,
  `residencial_7_mercantil_3` varchar(255) DEFAULT NULL,
  `residencial_7_laboral_1` varchar(255) DEFAULT NULL,
  `residencial_7_laboral_2` varchar(255) DEFAULT NULL,
  `residencial_7_laboral_3` varchar(255) DEFAULT NULL,
  `residencial_8_mercantil_1` varchar(255) DEFAULT NULL,
  `residencial_8_mercantil_2` varchar(255) DEFAULT NULL,
  `residencial_8_mercantil_3` varchar(255) DEFAULT NULL,
  `residencial_8_laboral_1` varchar(255) DEFAULT NULL,
  `residencial_8_laboral_2` varchar(255) DEFAULT NULL,
  `residencial_8_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_1_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_1_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_1_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_1_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_1_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_1_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_2_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_2_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_2_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_2_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_2_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_2_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_3_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_3_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_3_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_3_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_3_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_3_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_4_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_4_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_4_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_4_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_4_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_4_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_5_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_5_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_5_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_5_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_5_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_5_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_6_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_6_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_6_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_6_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_6_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_6_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_7_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_7_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_7_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_7_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_7_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_7_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_8_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_8_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_8_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_8_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_8_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_8_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_9_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_9_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_9_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_9_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_9_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_9_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_10_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_10_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_10_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_10_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_10_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_10_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_11_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_11_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_11_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_11_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_11_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_11_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_12_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_12_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_12_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_12_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_12_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_12_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_13_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_13_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_13_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_13_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_13_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_13_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_14_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_14_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_14_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_14_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_14_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_14_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_15_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_15_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_15_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_15_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_15_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_15_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_16_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_16_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_16_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_16_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_16_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_16_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_17_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_17_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_17_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_17_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_17_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_17_laboral_3` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for click_gerentes_introductores
-- ----------------------------
DROP TABLE IF EXISTS `click_gerentes_introductores`;
CREATE TABLE `click_gerentes_introductores` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `distribuidor` varchar(255) DEFAULT NULL,
  `gerente` varchar(255) DEFAULT NULL,
  `subgerente` varchar(255) DEFAULT NULL,
  `oficina` varchar(255) DEFAULT NULL,
  `codigo_interno` varchar(255) DEFAULT NULL,
  `residencial_1_mercantil_1` varchar(255) DEFAULT NULL,
  `residencial_1_mercantil_2` varchar(255) DEFAULT NULL,
  `residencial_1_mercantil_3` varchar(255) DEFAULT NULL,
  `residencial_1_laboral_1` varchar(255) DEFAULT NULL,
  `residencial_1_laboral_2` varchar(255) DEFAULT NULL,
  `residencial_1_laboral_3` varchar(255) DEFAULT NULL,
  `residencial_2_mercantil_1` varchar(255) DEFAULT NULL,
  `residencial_2_mercantil_2` varchar(255) DEFAULT NULL,
  `residencial_2_mercantil_3` varchar(255) DEFAULT NULL,
  `residencial_2_laboral_1` varchar(255) DEFAULT NULL,
  `residencial_2_laboral_2` varchar(255) DEFAULT NULL,
  `residencial_2_laboral_3` varchar(255) DEFAULT NULL,
  `residencial_3_mercantil_1` varchar(255) DEFAULT NULL,
  `residencial_3_mercantil_2` varchar(255) DEFAULT NULL,
  `residencial_3_mercantil_3` varchar(255) DEFAULT NULL,
  `residencial_3_laboral_1` varchar(255) DEFAULT NULL,
  `residencial_3_laboral_2` varchar(255) DEFAULT NULL,
  `residencial_3_laboral_3` varchar(255) DEFAULT NULL,
  `residencial_4_mercantil_1` varchar(255) DEFAULT NULL,
  `residencial_4_mercantil_2` varchar(255) DEFAULT NULL,
  `residencial_4_mercantil_3` varchar(255) DEFAULT NULL,
  `residencial_4_laboral_1` varchar(255) DEFAULT NULL,
  `residencial_4_laboral_2` varchar(255) DEFAULT NULL,
  `residencial_4_laboral_3` varchar(255) DEFAULT NULL,
  `residencial_5_mercantil_1` varchar(255) DEFAULT NULL,
  `residencial_5_mercantil_2` varchar(255) DEFAULT NULL,
  `residencial_5_mercantil_3` varchar(255) DEFAULT NULL,
  `residencial_5_laboral_1` varchar(255) DEFAULT NULL,
  `residencial_5_laboral_2` varchar(255) DEFAULT NULL,
  `residencial_5_laboral_3` varchar(255) DEFAULT NULL,
  `residencial_6_mercantil_1` varchar(255) DEFAULT NULL,
  `residencial_6_mercantil_2` varchar(255) DEFAULT NULL,
  `residencial_6_mercantil_3` varchar(255) DEFAULT NULL,
  `residencial_6_laboral_1` varchar(255) DEFAULT NULL,
  `residencial_6_laboral_2` varchar(255) DEFAULT NULL,
  `residencial_6_laboral_3` varchar(255) DEFAULT NULL,
  `residencial_7_mercantil_1` varchar(255) DEFAULT NULL,
  `residencial_7_mercantil_2` varchar(255) DEFAULT NULL,
  `residencial_7_mercantil_3` varchar(255) DEFAULT NULL,
  `residencial_7_laboral_1` varchar(255) DEFAULT NULL,
  `residencial_7_laboral_2` varchar(255) DEFAULT NULL,
  `residencial_7_laboral_3` varchar(255) DEFAULT NULL,
  `residencial_8_mercantil_1` varchar(255) DEFAULT NULL,
  `residencial_8_mercantil_2` varchar(255) DEFAULT NULL,
  `residencial_8_mercantil_3` varchar(255) DEFAULT NULL,
  `residencial_8_laboral_1` varchar(255) DEFAULT NULL,
  `residencial_8_laboral_2` varchar(255) DEFAULT NULL,
  `residencial_8_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_1_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_1_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_1_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_1_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_1_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_1_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_2_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_2_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_2_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_2_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_2_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_2_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_3_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_3_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_3_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_3_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_3_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_3_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_4_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_4_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_4_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_4_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_4_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_4_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_5_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_5_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_5_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_5_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_5_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_5_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_6_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_6_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_6_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_6_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_6_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_6_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_7_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_7_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_7_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_7_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_7_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_7_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_8_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_8_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_8_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_8_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_8_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_8_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_9_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_9_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_9_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_9_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_9_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_9_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_10_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_10_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_10_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_10_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_10_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_10_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_11_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_11_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_11_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_11_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_11_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_11_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_12_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_12_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_12_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_12_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_12_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_12_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_13_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_13_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_13_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_13_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_13_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_13_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_14_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_14_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_14_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_14_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_14_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_14_laboral_3` varchar(255) DEFAULT NULL,
  `negocio_15_mercantil_1` varchar(255) DEFAULT NULL,
  `negocio_15_mercantil_2` varchar(255) DEFAULT NULL,
  `negocio_15_mercantil_3` varchar(255) DEFAULT NULL,
  `negocio_15_laboral_1` varchar(255) DEFAULT NULL,
  `negocio_15_laboral_2` varchar(255) DEFAULT NULL,
  `negocio_15_laboral_3` varchar(255) DEFAULT NULL,
  `extra_16_mercantil_1` varchar(255) DEFAULT NULL,
  `extra_16_mercantil_2` varchar(255) DEFAULT NULL,
  `extra_16_mercantil_3` varchar(255) DEFAULT NULL,
  `extra_16_laboral_1` varchar(255) DEFAULT NULL,
  `extra_16_laboral_2` varchar(255) DEFAULT NULL,
  `extra_16_laboral_3` varchar(255) DEFAULT NULL,
  `extra_17_mercantil_1` varchar(255) DEFAULT NULL,
  `extra_17_mercantil_2` varchar(255) DEFAULT NULL,
  `extra_17_mercantil_3` varchar(255) DEFAULT NULL,
  `extra_17_laboral_1` varchar(255) DEFAULT NULL,
  `extra_17_laboral_2` varchar(255) DEFAULT NULL,
  `extra_17_laboral_3` varchar(255) DEFAULT NULL,
  `we_dia` varchar(255) DEFAULT NULL,
  `we_mes` varchar(255) DEFAULT NULL,
  `we_ano` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=279 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for cms_estadisticas
-- ----------------------------
DROP TABLE IF EXISTS `cms_estadisticas`;
CREATE TABLE `cms_estadisticas` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `tipo` varchar(255) DEFAULT NULL,
  `numero` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for cms_settings
-- ----------------------------
DROP TABLE IF EXISTS `cms_settings`;
CREATE TABLE `cms_settings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `site` varchar(255) DEFAULT NULL,
  `sitename` varchar(255) DEFAULT NULL,
  `reformas` enum('1','0') DEFAULT '0',
  `colorservidor` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for contratos
-- ----------------------------
DROP TABLE IF EXISTS `contratos`;
CREATE TABLE `contratos` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `tipo_tramitacion` varchar(255) DEFAULT 'CARGA INMEDIATA',
  `fecha_venta` varchar(255) DEFAULT NULL,
  `gerente` varchar(255) DEFAULT NULL,
  `subgerente` varchar(255) DEFAULT NULL,
  `oficina` varchar(255) DEFAULT NULL,
  `codigo_comercial` varchar(255) DEFAULT NULL,
  `nombre_titular` varchar(255) DEFAULT NULL,
  `apellidos_titular` varchar(255) DEFAULT NULL,
  `dni_cif_titular` varchar(255) DEFAULT NULL,
  `telefono_pref_1` varchar(255) DEFAULT NULL,
  `idioma` varchar(255) DEFAULT NULL,
  `telefono_pref_2` varchar(255) DEFAULT NULL,
  `correo_electron` varchar(255) DEFAULT NULL,
  `municipio_ps` varchar(255) DEFAULT NULL,
  `poblacion_ps` varchar(255) DEFAULT NULL,
  `tipo_via_ps` varchar(255) DEFAULT NULL,
  `calle_ps` varchar(255) DEFAULT NULL,
  `numero_ps` varchar(255) DEFAULT NULL,
  `escalera_ps` varchar(255) DEFAULT NULL,
  `piso_ps` varchar(255) DEFAULT NULL,
  `letra_ps` varchar(255) DEFAULT NULL,
  `cod_postal_ps` varchar(255) DEFAULT NULL,
  `pais_ps` varchar(255) DEFAULT 'ES - ESPANA',
  `aclaracion_direccion_ps` varchar(255) DEFAULT NULL,
  `estado_luz` varchar(255) DEFAULT 'NO',
  `estado_gas` varchar(255) DEFAULT 'NO',
  `tiene_fun_ps` varchar(255) DEFAULT 'NO',
  `plan_destino_luz` varchar(255) DEFAULT NULL,
  `plan_destino_gas` varchar(255) DEFAULT NULL,
  `plan_destino_fun` varchar(255) DEFAULT NULL,
  `vers_funciona` varchar(255) DEFAULT NULL,
  `modal_funciona` varchar(255) DEFAULT NULL,
  `tipo_alta_luz` varchar(255) DEFAULT NULL,
  `tipo_alta_gas` varchar(255) DEFAULT NULL,
  `tipo_alta_fun` varchar(255) DEFAULT NULL,
  `descuento_luz` varchar(255) DEFAULT NULL,
  `descuento_gas` varchar(255) DEFAULT NULL,
  `cod_verificacion_posterior` varchar(255) DEFAULT NULL,
  `cups_luz` varchar(255) DEFAULT NULL,
  `cups_gas` varchar(255) DEFAULT NULL,
  `tarifa_ref_luz` varchar(255) DEFAULT NULL,
  `tarifa_ref_gas` varchar(255) DEFAULT NULL,
  `tot_activa_luz` varchar(255) DEFAULT NULL,
  `fases` varchar(255) DEFAULT NULL,
  `maximetro` varchar(255) DEFAULT 'NO',
  `marca_caldera` varchar(255) DEFAULT NULL,
  `contrata_opcion_clima` varchar(255) DEFAULT NULL,
  `marca_aparato_climatizacion` varchar(255) DEFAULT NULL,
  `contrata_efactura` varchar(255) DEFAULT NULL,
  `cnae` varchar(255) DEFAULT NULL,
  `direccion_cliente` varchar(255) DEFAULT NULL,
  `direccion_envio_facturas` varchar(255) DEFAULT NULL,
  `bloqueo_datos_lopd` varchar(255) DEFAULT NULL,
  `representante_nombre` varchar(255) DEFAULT NULL,
  `representante_apellidos` varchar(255) DEFAULT NULL,
  `dni_cif_representante` varchar(255) DEFAULT NULL,
  `relacion_representante_titular` varchar(255) DEFAULT NULL,
  `aporta_cie` varchar(255) DEFAULT NULL,
  `cod_venta_espontanea` varchar(255) DEFAULT NULL,
  `cliente_provincia_otra` varchar(255) DEFAULT NULL,
  `cliente_municipio_otra` varchar(255) DEFAULT NULL,
  `cliente_poblacion_otra` varchar(255) DEFAULT NULL,
  `cliente_tipo_via_otra` varchar(255) DEFAULT NULL,
  `cliente_calle_otra` varchar(255) DEFAULT NULL,
  `cliente_numero_otra` varchar(255) DEFAULT NULL,
  `cliente_escalera_otra` varchar(255) DEFAULT NULL,
  `cliente_piso_otra` varchar(255) DEFAULT NULL,
  `cliente_letra_otra` varchar(255) DEFAULT NULL,
  `cliente_cod_postal_otra` varchar(255) DEFAULT NULL,
  `cliente_pais_otra` varchar(255) DEFAULT 'ES - ESPANA',
  `provincia_ef_otra` varchar(255) DEFAULT NULL,
  `municipio_ef_otra` varchar(255) DEFAULT NULL,
  `poblacion_ef_otra` varchar(255) DEFAULT NULL,
  `tipo_via_ef_otra` varchar(255) DEFAULT NULL,
  `calle_ef_otra` varchar(255) DEFAULT NULL,
  `numero_ef_otra` varchar(255) DEFAULT NULL,
  `escalera_ef_otra` varchar(255) DEFAULT NULL,
  `piso_ef_otra` varchar(255) DEFAULT NULL,
  `letra_ef_otra` varchar(255) DEFAULT NULL,
  `cod_postal_ef_otra` varchar(255) DEFAULT NULL,
  `pais_ef_otra` varchar(255) DEFAULT 'ES - ESPANA',
  `tipo_alta_luz_ct` varchar(255) DEFAULT NULL,
  `marca_socia` varchar(255) DEFAULT NULL,
  `tarjeta_socia` varchar(255) DEFAULT NULL,
  `redy` varchar(255) DEFAULT NULL,
  `version_redy` varchar(255) DEFAULT NULL,
  `factura_segura` varchar(255) DEFAULT NULL,
  `edp_click` varchar(255) DEFAULT NULL,
  `date` varchar(255) DEFAULT NULL,
  `we` varchar(255) DEFAULT NULL,
  `tipo_de_funciona` varchar(255) DEFAULT NULL,
  `precio_luz_edp` varchar(255) DEFAULT NULL,
  `precio_gas_edp` varchar(255) DEFAULT NULL,
  `ccc_1` varchar(255) DEFAULT NULL,
  `ccc_2` varchar(255) DEFAULT NULL,
  `ccc_3` varchar(255) DEFAULT NULL,
  `ccc_4` varchar(255) DEFAULT NULL,
  `fechaemision` varchar(255) DEFAULT NULL,
  `potencia_p1` varchar(255) DEFAULT NULL,
  `potencia_p2` varchar(255) DEFAULT NULL,
  `potencia_p3` varchar(255) DEFAULT NULL,
  `cig` varchar(255) DEFAULT NULL,
  `edited_contract_date` varchar(255) DEFAULT NULL,
  `edited_contract_user` varchar(255) DEFAULT NULL,
  `tipo_contrato` varchar(255) DEFAULT NULL,
  `formula` varchar(255) DEFAULT NULL,
  `formula1` varchar(255) DEFAULT NULL,
  `formula2` varchar(255) DEFAULT NULL,
  `funciona` varchar(255) DEFAULT NULL,
  `edited_contract_reason` varchar(255) DEFAULT NULL,
  `fecha_contrato_intro` varchar(255) DEFAULT NULL,
  `user_contrato_intro` varchar(255) DEFAULT NULL,
  `we_dia` varchar(255) DEFAULT NULL,
  `we_mes` varchar(255) DEFAULT NULL,
  `we_ano` varchar(255) DEFAULT NULL,
  `lopd` varchar(255) DEFAULT NULL,
  `consumo_pyme` varchar(255) DEFAULT NULL,
  `intro_dia` varchar(255) DEFAULT NULL,
  `intro_mes` varchar(255) DEFAULT NULL,
  `intro_ano` varchar(255) DEFAULT NULL,
  `estado_contrato` varchar(255) DEFAULT 'INTRODUCIDO',
  `deleted` enum('1','0') DEFAULT '0',
  `cod_verificacion` varchar(255) DEFAULT NULL,
  `subgerente2` varchar(255) DEFAULT NULL,
  `impl` varchar(255) DEFAULT 'SI',
  `impl_explicito` varchar(255) DEFAULT NULL,
  `motivo` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=26922 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for contratos_borrados
-- ----------------------------
DROP TABLE IF EXISTS `contratos_borrados`;
CREATE TABLE `contratos_borrados` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `tipo_tramitacion` varchar(255) DEFAULT 'CARGA INMEDIATA',
  `fecha_venta` varchar(255) DEFAULT NULL,
  `gerente` varchar(255) DEFAULT NULL,
  `subgerente` varchar(255) DEFAULT NULL,
  `oficina` varchar(255) DEFAULT NULL,
  `codigo_comercial` varchar(255) DEFAULT NULL,
  `nombre_titular` varchar(255) DEFAULT NULL,
  `apellidos_titular` varchar(255) DEFAULT NULL,
  `dni_cif_titular` varchar(255) DEFAULT NULL,
  `telefono_pref_1` varchar(255) DEFAULT NULL,
  `idioma` varchar(255) DEFAULT NULL,
  `telefono_pref_2` varchar(255) DEFAULT NULL,
  `correo_electron` varchar(255) DEFAULT NULL,
  `municipio_ps` varchar(255) DEFAULT NULL,
  `poblacion_ps` varchar(255) DEFAULT NULL,
  `tipo_via_ps` varchar(255) DEFAULT NULL,
  `calle_ps` varchar(255) DEFAULT NULL,
  `numero_ps` varchar(255) DEFAULT NULL,
  `escalera_ps` varchar(255) DEFAULT NULL,
  `piso_ps` varchar(255) DEFAULT NULL,
  `letra_ps` varchar(255) DEFAULT NULL,
  `cod_postal_ps` varchar(255) DEFAULT NULL,
  `pais_ps` varchar(255) DEFAULT 'ES - ESPANA',
  `aclaracion_direccion_ps` varchar(255) DEFAULT NULL,
  `estado_luz` varchar(255) DEFAULT 'NO',
  `estado_gas` varchar(255) DEFAULT 'NO',
  `tiene_fun_ps` varchar(255) DEFAULT 'NO',
  `plan_destino_luz` varchar(255) DEFAULT NULL,
  `plan_destino_gas` varchar(255) DEFAULT NULL,
  `plan_destino_fun` varchar(255) DEFAULT NULL,
  `vers_funciona` varchar(255) DEFAULT NULL,
  `modal_funciona` varchar(255) DEFAULT NULL,
  `tipo_alta_luz` varchar(255) DEFAULT 'NA',
  `tipo_alta_gas` varchar(255) DEFAULT 'NA',
  `tipo_alta_fun` varchar(255) DEFAULT NULL,
  `descuento_luz` varchar(255) DEFAULT NULL,
  `descuento_gas` varchar(255) DEFAULT NULL,
  `cod_verificacion` varchar(255) DEFAULT NULL,
  `cod_verificacion_posterior` varchar(255) DEFAULT NULL,
  `cups_luz` varchar(255) DEFAULT NULL,
  `cups_gas` varchar(255) DEFAULT NULL,
  `tarifa_ref_luz` varchar(255) DEFAULT NULL,
  `tarifa_ref_gas` varchar(255) DEFAULT NULL,
  `tot_activa_luz` varchar(255) DEFAULT NULL,
  `fases` varchar(255) DEFAULT NULL,
  `maximetro` varchar(255) DEFAULT NULL,
  `marca_caldera` varchar(255) DEFAULT NULL,
  `contrata_opcion_clima` varchar(255) DEFAULT NULL,
  `marca_aparato_climatizacion` varchar(255) DEFAULT NULL,
  `contrata_efactura` varchar(255) DEFAULT NULL,
  `cnae` varchar(255) DEFAULT NULL,
  `direccion_cliente` varchar(255) DEFAULT NULL,
  `direccion_envio_facturas` varchar(255) DEFAULT NULL,
  `bloqueo_datos_lopd` varchar(255) DEFAULT NULL,
  `representante_nombre` varchar(255) DEFAULT NULL,
  `representante_apellidos` varchar(255) DEFAULT NULL,
  `dni_cif_representante` varchar(255) DEFAULT NULL,
  `relacion_representante_titular` varchar(255) DEFAULT NULL,
  `aporta_cie` varchar(255) DEFAULT NULL,
  `cod_venta_espontanea` varchar(255) DEFAULT NULL,
  `cliente_provincia_otra` varchar(255) DEFAULT NULL,
  `cliente_municipio_otra` varchar(255) DEFAULT NULL,
  `cliente_poblacion_otra` varchar(255) DEFAULT NULL,
  `cliente_tipo_via_otra` varchar(255) DEFAULT NULL,
  `cliente_calle_otra` varchar(255) DEFAULT NULL,
  `cliente_numero_otra` varchar(255) DEFAULT NULL,
  `cliente_escalera_otra` varchar(255) DEFAULT NULL,
  `cliente_piso_otra` varchar(255) DEFAULT NULL,
  `cliente_letra_otra` varchar(255) DEFAULT NULL,
  `cliente_cod_postal_otra` varchar(255) DEFAULT NULL,
  `cliente_pais_otra` varchar(255) DEFAULT 'ES - ESPANA',
  `provincia_ef_otra` varchar(255) DEFAULT NULL,
  `municipio_ef_otra` varchar(255) DEFAULT NULL,
  `poblacion_ef_otra` varchar(255) DEFAULT NULL,
  `tipo_via_ef_otra` varchar(255) DEFAULT NULL,
  `calle_ef_otra` varchar(255) DEFAULT NULL,
  `numero_ef_otra` varchar(255) DEFAULT NULL,
  `escalera_ef_otra` varchar(255) DEFAULT NULL,
  `piso_ef_otra` varchar(255) DEFAULT NULL,
  `letra_ef_otra` varchar(255) DEFAULT NULL,
  `cod_postal_ef_otra` varchar(255) DEFAULT NULL,
  `pais_ef_otra` varchar(255) DEFAULT 'ES - ESPANA',
  `tipo_alta_luz_ct` varchar(255) DEFAULT NULL,
  `marca_socia` varchar(255) DEFAULT NULL,
  `tarjeta_socia` varchar(255) DEFAULT NULL,
  `redy` varchar(255) DEFAULT NULL,
  `version_redy` varchar(255) DEFAULT NULL,
  `factura_segura` varchar(255) DEFAULT NULL,
  `edp_click` varchar(255) DEFAULT NULL,
  `date` varchar(255) DEFAULT NULL,
  `we` varchar(255) DEFAULT NULL,
  `tipo_de_funciona` varchar(255) DEFAULT NULL,
  `precio_luz_edp` varchar(255) DEFAULT NULL,
  `precio_gas_edp` varchar(255) DEFAULT NULL,
  `ccc_1` varchar(255) DEFAULT NULL,
  `ccc_2` varchar(255) DEFAULT NULL,
  `ccc_3` varchar(255) DEFAULT NULL,
  `ccc_4` varchar(255) DEFAULT NULL,
  `fechaemision` varchar(255) DEFAULT NULL,
  `potencia_p1` varchar(255) DEFAULT NULL,
  `potencia_p2` varchar(255) DEFAULT NULL,
  `potencia_p3` varchar(255) DEFAULT NULL,
  `cig` varchar(255) DEFAULT NULL,
  `edited_contract_date` varchar(255) DEFAULT NULL,
  `edited_contract_user` varchar(255) DEFAULT NULL,
  `tipo_contrato` varchar(255) DEFAULT NULL,
  `formula` varchar(255) DEFAULT NULL,
  `formula2` varchar(255) DEFAULT NULL,
  `funciona` varchar(255) DEFAULT NULL,
  `edited_contract_reason` varchar(255) DEFAULT NULL,
  `fecha_contrato_intro` varchar(255) DEFAULT NULL,
  `user_contrato_intro` varchar(255) DEFAULT NULL,
  `we_dia` varchar(255) DEFAULT NULL,
  `we_mes` varchar(255) DEFAULT NULL,
  `we_ano` varchar(255) DEFAULT NULL,
  `lopd` varchar(255) DEFAULT NULL,
  `consumo_pyme` varchar(255) DEFAULT NULL,
  `intro_dia` varchar(255) DEFAULT NULL,
  `intro_mes` varchar(255) DEFAULT NULL,
  `intro_ano` varchar(255) DEFAULT NULL,
  `estado_contrato` varchar(255) DEFAULT 'INTRODUCIDO',
  `deleted` enum('1','0') DEFAULT '0',
  `subgerente2` varchar(255) DEFAULT NULL,
  `impl` varchar(255) DEFAULT 'SI',
  `impl_explicito` varchar(255) DEFAULT NULL,
  `motivo` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for contratos_calderas
-- ----------------------------
DROP TABLE IF EXISTS `contratos_calderas`;
CREATE TABLE `contratos_calderas` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `caldera` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=152 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for contratos_copy
-- ----------------------------
DROP TABLE IF EXISTS `contratos_copy`;
CREATE TABLE `contratos_copy` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `tipo_tramitacion` varchar(255) DEFAULT 'CARGA INMEDIATA',
  `fecha_venta` varchar(255) DEFAULT NULL,
  `gerente` varchar(255) DEFAULT NULL,
  `subgerente` varchar(255) DEFAULT NULL,
  `oficina` varchar(255) DEFAULT NULL,
  `codigo_comercial` varchar(255) DEFAULT NULL,
  `nombre_titular` varchar(255) DEFAULT NULL,
  `apellidos_titular` varchar(255) DEFAULT NULL,
  `dni_cif_titular` varchar(255) DEFAULT NULL,
  `telefono_pref_1` varchar(255) DEFAULT NULL,
  `idioma` varchar(255) DEFAULT NULL,
  `telefono_pref_2` varchar(255) DEFAULT NULL,
  `correo_electron` varchar(255) DEFAULT NULL,
  `municipio_ps` varchar(255) DEFAULT NULL,
  `poblacion_ps` varchar(255) DEFAULT NULL,
  `tipo_via_ps` varchar(255) DEFAULT NULL,
  `calle_ps` varchar(255) DEFAULT NULL,
  `numero_ps` varchar(255) DEFAULT NULL,
  `escalera_ps` varchar(255) DEFAULT NULL,
  `piso_ps` varchar(255) DEFAULT NULL,
  `letra_ps` varchar(255) DEFAULT NULL,
  `cod_postal_ps` varchar(255) DEFAULT NULL,
  `pais_ps` varchar(255) DEFAULT 'ES - ESPANA',
  `aclaracion_direccion_ps` varchar(255) DEFAULT NULL,
  `estado_luz` varchar(255) DEFAULT 'NO',
  `estado_gas` varchar(255) DEFAULT 'NO',
  `tiene_fun_ps` varchar(255) DEFAULT 'NO',
  `plan_destino_luz` varchar(255) DEFAULT NULL,
  `plan_destino_gas` varchar(255) DEFAULT NULL,
  `plan_destino_fun` varchar(255) DEFAULT NULL,
  `vers_funciona` varchar(255) DEFAULT NULL,
  `modal_funciona` varchar(255) DEFAULT NULL,
  `tipo_alta_luz` varchar(255) DEFAULT NULL,
  `tipo_alta_gas` varchar(255) DEFAULT NULL,
  `tipo_alta_fun` varchar(255) DEFAULT NULL,
  `descuento_luz` varchar(255) DEFAULT NULL,
  `descuento_gas` varchar(255) DEFAULT NULL,
  `cod_verificacion_posterior` varchar(255) DEFAULT NULL,
  `cups_luz` varchar(255) DEFAULT NULL,
  `cups_gas` varchar(255) DEFAULT NULL,
  `tarifa_ref_luz` varchar(255) DEFAULT NULL,
  `tarifa_ref_gas` varchar(255) DEFAULT NULL,
  `tot_activa_luz` varchar(255) DEFAULT NULL,
  `fases` varchar(255) DEFAULT NULL,
  `maximetro` varchar(255) DEFAULT 'NO',
  `marca_caldera` varchar(255) DEFAULT NULL,
  `contrata_opcion_clima` varchar(255) DEFAULT NULL,
  `marca_aparato_climatizacion` varchar(255) DEFAULT NULL,
  `contrata_efactura` varchar(255) DEFAULT NULL,
  `cnae` varchar(255) DEFAULT NULL,
  `direccion_cliente` varchar(255) DEFAULT NULL,
  `direccion_envio_facturas` varchar(255) DEFAULT NULL,
  `bloqueo_datos_lopd` varchar(255) DEFAULT NULL,
  `representante_nombre` varchar(255) DEFAULT NULL,
  `representante_apellidos` varchar(255) DEFAULT NULL,
  `dni_cif_representante` varchar(255) DEFAULT NULL,
  `relacion_representante_titular` varchar(255) DEFAULT NULL,
  `aporta_cie` varchar(255) DEFAULT NULL,
  `cod_venta_espontanea` varchar(255) DEFAULT NULL,
  `cliente_provincia_otra` varchar(255) DEFAULT NULL,
  `cliente_municipio_otra` varchar(255) DEFAULT NULL,
  `cliente_poblacion_otra` varchar(255) DEFAULT NULL,
  `cliente_tipo_via_otra` varchar(255) DEFAULT NULL,
  `cliente_calle_otra` varchar(255) DEFAULT NULL,
  `cliente_numero_otra` varchar(255) DEFAULT NULL,
  `cliente_escalera_otra` varchar(255) DEFAULT NULL,
  `cliente_piso_otra` varchar(255) DEFAULT NULL,
  `cliente_letra_otra` varchar(255) DEFAULT NULL,
  `cliente_cod_postal_otra` varchar(255) DEFAULT NULL,
  `cliente_pais_otra` varchar(255) DEFAULT 'ES - ESPANA',
  `provincia_ef_otra` varchar(255) DEFAULT NULL,
  `municipio_ef_otra` varchar(255) DEFAULT NULL,
  `poblacion_ef_otra` varchar(255) DEFAULT NULL,
  `tipo_via_ef_otra` varchar(255) DEFAULT NULL,
  `calle_ef_otra` varchar(255) DEFAULT NULL,
  `numero_ef_otra` varchar(255) DEFAULT NULL,
  `escalera_ef_otra` varchar(255) DEFAULT NULL,
  `piso_ef_otra` varchar(255) DEFAULT NULL,
  `letra_ef_otra` varchar(255) DEFAULT NULL,
  `cod_postal_ef_otra` varchar(255) DEFAULT NULL,
  `pais_ef_otra` varchar(255) DEFAULT 'ES - ESPANA',
  `tipo_alta_luz_ct` varchar(255) DEFAULT NULL,
  `marca_socia` varchar(255) DEFAULT NULL,
  `tarjeta_socia` varchar(255) DEFAULT NULL,
  `redy` varchar(255) DEFAULT NULL,
  `version_redy` varchar(255) DEFAULT NULL,
  `factura_segura` varchar(255) DEFAULT NULL,
  `edp_click` varchar(255) DEFAULT NULL,
  `date` varchar(255) DEFAULT NULL,
  `we` varchar(255) DEFAULT NULL,
  `tipo_de_funciona` varchar(255) DEFAULT NULL,
  `precio_luz_edp` varchar(255) DEFAULT NULL,
  `precio_gas_edp` varchar(255) DEFAULT NULL,
  `ccc_1` varchar(255) DEFAULT NULL,
  `ccc_2` varchar(255) DEFAULT NULL,
  `ccc_3` varchar(255) DEFAULT NULL,
  `ccc_4` varchar(255) DEFAULT NULL,
  `fechaemision` varchar(255) DEFAULT NULL,
  `potencia_p1` varchar(255) DEFAULT NULL,
  `potencia_p2` varchar(255) DEFAULT NULL,
  `potencia_p3` varchar(255) DEFAULT NULL,
  `cig` varchar(255) DEFAULT NULL,
  `edited_contract_date` varchar(255) DEFAULT NULL,
  `edited_contract_user` varchar(255) DEFAULT NULL,
  `tipo_contrato` varchar(255) DEFAULT NULL,
  `formula` varchar(255) DEFAULT NULL,
  `formula1` varchar(255) DEFAULT NULL,
  `formula2` varchar(255) DEFAULT NULL,
  `funciona` varchar(255) DEFAULT NULL,
  `edited_contract_reason` varchar(255) DEFAULT NULL,
  `fecha_contrato_intro` varchar(255) DEFAULT NULL,
  `user_contrato_intro` varchar(255) DEFAULT NULL,
  `we_dia` varchar(255) DEFAULT NULL,
  `we_mes` varchar(255) DEFAULT NULL,
  `we_ano` varchar(255) DEFAULT NULL,
  `lopd` varchar(255) DEFAULT NULL,
  `consumo_pyme` varchar(255) DEFAULT NULL,
  `intro_dia` varchar(255) DEFAULT NULL,
  `intro_mes` varchar(255) DEFAULT NULL,
  `intro_ano` varchar(255) DEFAULT NULL,
  `estado_contrato` varchar(255) DEFAULT 'INTRODUCIDO',
  `deleted` enum('1','0') DEFAULT '0',
  `cod_verificacion` varchar(255) DEFAULT NULL,
  `subgerente2` varchar(255) DEFAULT NULL,
  `impl` varchar(255) DEFAULT 'SI',
  `impl_explicito` varchar(255) DEFAULT NULL,
  `motivo` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=79 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for contratos_estado_historial
-- ----------------------------
DROP TABLE IF EXISTS `contratos_estado_historial`;
CREATE TABLE `contratos_estado_historial` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `type` varchar(255) DEFAULT NULL,
  `contrato_id` int(11) DEFAULT NULL,
  `user` varchar(255) DEFAULT NULL,
  `fecha` varchar(255) DEFAULT NULL,
  `estado` varchar(255) DEFAULT NULL,
  `cod_verificacion` varchar(255) DEFAULT NULL,
  `referencia` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=16041 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for contratos_importados
-- ----------------------------
DROP TABLE IF EXISTS `contratos_importados`;
CREATE TABLE `contratos_importados` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `tipo_tramitacion` varchar(255) DEFAULT 'CARGA INMEDIATA',
  `fecha_venta` varchar(255) DEFAULT NULL,
  `gerente` varchar(255) DEFAULT NULL,
  `subgerente` varchar(255) DEFAULT NULL,
  `oficina` varchar(255) DEFAULT NULL,
  `codigo_comercial` varchar(255) DEFAULT NULL,
  `nombre_titular` varchar(255) DEFAULT NULL,
  `apellidos_titular` varchar(255) DEFAULT NULL,
  `dni_cif_titular` varchar(255) DEFAULT NULL,
  `telefono_pref_1` varchar(255) DEFAULT NULL,
  `idioma` varchar(255) DEFAULT NULL,
  `telefono_pref_2` varchar(255) DEFAULT NULL,
  `correo_electron` varchar(255) DEFAULT NULL,
  `municipio_ps` varchar(255) DEFAULT NULL,
  `poblacion_ps` varchar(255) DEFAULT NULL,
  `tipo_via_ps` varchar(255) DEFAULT NULL,
  `calle_ps` varchar(255) DEFAULT NULL,
  `numero_ps` varchar(255) DEFAULT NULL,
  `escalera_ps` varchar(255) DEFAULT NULL,
  `piso_ps` varchar(255) DEFAULT NULL,
  `letra_ps` varchar(255) DEFAULT NULL,
  `cod_postal_ps` varchar(255) DEFAULT NULL,
  `pais_ps` varchar(255) DEFAULT 'ES - ESPANA',
  `aclaracion_direccion_ps` varchar(255) DEFAULT NULL,
  `estado_luz` varchar(255) DEFAULT 'NO',
  `estado_gas` varchar(255) DEFAULT 'NO',
  `tiene_fun_ps` varchar(255) DEFAULT 'NO',
  `plan_destino_luz` varchar(255) DEFAULT NULL,
  `plan_destino_gas` varchar(255) DEFAULT NULL,
  `plan_destino_fun` varchar(255) DEFAULT NULL,
  `vers_funciona` varchar(255) DEFAULT NULL,
  `modal_funciona` varchar(255) DEFAULT NULL,
  `tipo_alta_luz` varchar(255) DEFAULT 'NA',
  `tipo_alta_gas` varchar(255) DEFAULT 'NA',
  `tipo_alta_fun` varchar(255) DEFAULT NULL,
  `descuento_luz` varchar(255) DEFAULT NULL,
  `descuento_gas` varchar(255) DEFAULT NULL,
  `cod_verificacion` varchar(255) DEFAULT NULL,
  `cups_luz` varchar(255) DEFAULT NULL,
  `cups_gas` varchar(255) DEFAULT NULL,
  `tarifa_ref_luz` varchar(255) DEFAULT NULL,
  `tarifa_ref_gas` varchar(255) DEFAULT NULL,
  `tot_activa_luz` varchar(255) DEFAULT NULL,
  `fases` varchar(255) DEFAULT NULL,
  `maximetro` varchar(255) DEFAULT NULL,
  `marca_caldera` varchar(255) DEFAULT NULL,
  `contrata_opcion_clima` varchar(255) DEFAULT NULL,
  `marca_aparato_climatizacion` varchar(255) DEFAULT NULL,
  `contrata_efactura` varchar(255) DEFAULT NULL,
  `cnae` varchar(255) DEFAULT NULL,
  `direccion_cliente` varchar(255) DEFAULT NULL,
  `direccion_envio_facturas` varchar(255) DEFAULT NULL,
  `bloqueo_datos_lopd` varchar(255) DEFAULT NULL,
  `representante_nombre` varchar(255) DEFAULT NULL,
  `representante_apellidos` varchar(255) DEFAULT NULL,
  `dni_cif_representante` varchar(255) DEFAULT NULL,
  `relacion_representante_titular` varchar(255) DEFAULT NULL,
  `aporta_cie` varchar(255) DEFAULT NULL,
  `cod_venta_espontanea` varchar(255) DEFAULT NULL,
  `cliente_provincia_otra` varchar(255) DEFAULT NULL,
  `cliente_municipio_otra` varchar(255) DEFAULT NULL,
  `cliente_poblacion_otra` varchar(255) DEFAULT NULL,
  `cliente_tipo_via_otra` varchar(255) DEFAULT NULL,
  `cliente_calle_otra` varchar(255) DEFAULT NULL,
  `cliente_numero_otra` varchar(255) DEFAULT NULL,
  `cliente_escalera_otra` varchar(255) DEFAULT NULL,
  `cliente_piso_otra` varchar(255) DEFAULT NULL,
  `cliente_letra_otra` varchar(255) DEFAULT NULL,
  `cliente_cod_postal_otra` varchar(255) DEFAULT NULL,
  `cliente_pais_otra` varchar(255) DEFAULT 'ES - ESPANA',
  `provincia_ef_otra` varchar(255) DEFAULT NULL,
  `municipio_ef_otra` varchar(255) DEFAULT NULL,
  `poblacion_ef_otra` varchar(255) DEFAULT NULL,
  `tipo_via_ef_otra` varchar(255) DEFAULT NULL,
  `calle_ef_otra` varchar(255) DEFAULT NULL,
  `numero_ef_otra` varchar(255) DEFAULT NULL,
  `escalera_ef_otra` varchar(255) DEFAULT NULL,
  `piso_ef_otra` varchar(255) DEFAULT NULL,
  `letra_ef_otra` varchar(255) DEFAULT NULL,
  `cod_postal_ef_otra` varchar(255) DEFAULT NULL,
  `pais_ef_otra` varchar(255) DEFAULT 'ES - ESPANA',
  `tipo_alta_luz_ct` varchar(255) DEFAULT NULL,
  `marca_socia` varchar(255) DEFAULT NULL,
  `tarjeta_socia` varchar(255) DEFAULT NULL,
  `redy` varchar(255) DEFAULT NULL,
  `version_redy` varchar(255) DEFAULT NULL,
  `factura_segura` varchar(255) DEFAULT NULL,
  `edp_click` varchar(255) DEFAULT NULL,
  `date` varchar(255) DEFAULT NULL,
  `we` varchar(255) DEFAULT NULL,
  `tipo_de_funciona` varchar(255) DEFAULT NULL,
  `precio_luz_edp` varchar(255) DEFAULT NULL,
  `precio_gas_edp` varchar(255) DEFAULT NULL,
  `ccc_1` varchar(255) DEFAULT NULL,
  `ccc_2` varchar(255) DEFAULT NULL,
  `ccc_3` varchar(255) DEFAULT NULL,
  `ccc_4` varchar(255) DEFAULT NULL,
  `fechaemision` varchar(255) DEFAULT NULL,
  `potencia_p1` varchar(255) DEFAULT NULL,
  `potencia_p2` varchar(255) DEFAULT NULL,
  `potencia_p3` varchar(255) DEFAULT NULL,
  `cig` varchar(255) DEFAULT NULL,
  `edited_contract_date` varchar(255) DEFAULT NULL,
  `edited_contract_user` varchar(255) DEFAULT NULL,
  `tipo_contrato` varchar(255) DEFAULT NULL,
  `formula` varchar(255) DEFAULT NULL,
  `formula1` varchar(255) DEFAULT NULL,
  `formula2` varchar(255) DEFAULT NULL,
  `funciona` varchar(255) DEFAULT NULL,
  `edited_contract_reason` varchar(255) DEFAULT NULL,
  `fecha_contrato_intro` varchar(255) DEFAULT NULL,
  `user_contrato_intro` varchar(255) DEFAULT NULL,
  `we_dia` varchar(255) DEFAULT NULL,
  `we_mes` varchar(255) DEFAULT NULL,
  `we_ano` varchar(255) DEFAULT NULL,
  `consumo_pyme` varchar(255) DEFAULT NULL,
  `intro_dia` varchar(255) DEFAULT NULL,
  `intro_mes` varchar(255) DEFAULT NULL,
  `intro_ano` varchar(255) DEFAULT NULL,
  `estado_contrato` varchar(255) DEFAULT 'INTRODUCIDO',
  `revisado_contrato1` varchar(255) DEFAULT NULL,
  `revisado_contrato2` varchar(255) DEFAULT NULL,
  `revisado_contrato3` varchar(255) DEFAULT NULL,
  `revisado_contrato4` varchar(255) DEFAULT NULL,
  `revisado_contrato5` varchar(255) DEFAULT NULL,
  `revisado_contrato6` varchar(255) DEFAULT NULL,
  `revisado_contrato7` varchar(255) DEFAULT NULL,
  `revisado_contrato8` varchar(255) DEFAULT NULL,
  `revisado_contrato9` varchar(255) DEFAULT NULL,
  `revisado_contrato10` varchar(255) DEFAULT NULL,
  `deleted` enum('1','0') DEFAULT '0',
  `subgerente2` varchar(255) DEFAULT NULL,
  `impl` varchar(255) DEFAULT 'SI',
  `impl_explicito` varchar(255) DEFAULT NULL,
  `motivo` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8218 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for contratos_provincias
-- ----------------------------
DROP TABLE IF EXISTS `contratos_provincias`;
CREATE TABLE `contratos_provincias` (
  `id` int(11) NOT NULL,
  `codigo_postal` varchar(255) DEFAULT NULL,
  `provincia` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for contratos_voids
-- ----------------------------
DROP TABLE IF EXISTS `contratos_voids`;
CREATE TABLE `contratos_voids` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `tipo_tramitacion` varchar(255) DEFAULT 'CARGA INMEDIATA',
  `fecha_venta` varchar(255) DEFAULT NULL,
  `gerente` varchar(255) DEFAULT NULL,
  `subgerente` varchar(255) DEFAULT NULL,
  `oficina` varchar(255) DEFAULT NULL,
  `codigo_comercial` varchar(255) DEFAULT NULL,
  `nombre_titular` varchar(255) DEFAULT NULL,
  `apellidos_titular` varchar(255) DEFAULT NULL,
  `dni_cif_titular` varchar(255) DEFAULT NULL,
  `plan_destino_luz` varchar(255) DEFAULT NULL,
  `plan_destino_gas` varchar(255) DEFAULT NULL,
  `plan_destino_fun` varchar(255) DEFAULT NULL,
  `cups_luz` varchar(255) DEFAULT NULL,
  `cups_gas` varchar(255) DEFAULT NULL,
  `cod_verificacion_posterior` varchar(255) DEFAULT NULL,
  `cod_verificacion` varchar(255) DEFAULT NULL,
  `cig` varchar(255) DEFAULT NULL,
  `estado` varchar(255) DEFAULT NULL,
  `motivo` varchar(255) DEFAULT NULL,
  `we_dia` varchar(255) DEFAULT NULL,
  `we_mes` varchar(255) DEFAULT NULL,
  `we_ano` varchar(255) DEFAULT NULL,
  `intro_dia` varchar(255) DEFAULT NULL,
  `intro_mes` varchar(255) DEFAULT NULL,
  `intro_ano` varchar(255) DEFAULT NULL,
  `intro_user` varchar(255) DEFAULT NULL,
  `telefono_pref_1` varchar(255) DEFAULT NULL,
  `tipo_contrato` varchar(255) DEFAULT NULL,
  `formula` varchar(255) DEFAULT NULL,
  `formula1` varchar(255) DEFAULT NULL,
  `formula2` varchar(255) DEFAULT NULL,
  `funciona` varchar(255) DEFAULT NULL,
  `vers_funciona` varchar(255) DEFAULT NULL,
  `modal_funciona` varchar(255) DEFAULT NULL,
  `subgerente2` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2992 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for historial
-- ----------------------------
DROP TABLE IF EXISTS `historial`;
CREATE TABLE `historial` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `type` enum('new_contract','edit_contract','delete_contract','new_void','edit_void','new_comercial','delete_comercial','edit_comercial','delete_void') DEFAULT NULL,
  `motivo` varchar(999) DEFAULT NULL,
  `contract_id` varchar(255) DEFAULT NULL,
  `user` varchar(255) DEFAULT NULL,
  `date` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=17250 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for licencias
-- ----------------------------
DROP TABLE IF EXISTS `licencias`;
CREATE TABLE `licencias` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `clave_licencia` varchar(255) DEFAULT NULL,
  `fecha_inicio` datetime DEFAULT NULL,
  `fecha_fin` datetime DEFAULT NULL,
  `comprador` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for messages
-- ----------------------------
DROP TABLE IF EXISTS `messages`;
CREATE TABLE `messages` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_from` varchar(255) DEFAULT NULL,
  `user_to` varchar(255) DEFAULT NULL,
  `message` varchar(9999) DEFAULT NULL,
  `date` datetime DEFAULT NULL,
  `visibility` enum('1','0') DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for ranks
-- ----------------------------
DROP TABLE IF EXISTS `ranks`;
CREATE TABLE `ranks` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(255) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `rank` varchar(255) DEFAULT '1',
  `so` varchar(255) DEFAULT NULL,
  `ip` varchar(255) DEFAULT NULL,
  `last_online` varchar(255) DEFAULT NULL,
  `banned` enum('1','0') DEFAULT '0',
  `profile` varchar(255) DEFAULT NULL,
  `background` varchar(255) DEFAULT NULL,
  `nombre` varchar(255) DEFAULT NULL,
  `primer_apellido` varchar(255) DEFAULT NULL,
  `segundo_apellido` varchar(255) DEFAULT NULL,
  `view_comerciales` enum('0','1') DEFAULT '0',
  `edit_comerciales` enum('0','1') DEFAULT '0',
  `view_estados_contratos` enum('0','1') DEFAULT '0',
  `view_pagos` enum('0','1') DEFAULT '0',
  `edit_pagos` enum('0','1') DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=latin1;
